getzep/zep

- docker-compose.yaml
> Docker compose containers

- go.mod
- go.sum
- pkg/llms/embeddings_openai.go
- pkg/llms/llm_openai.go
> add retry and timeout to openai calls

- .github/workflows/docker-publish.yml
- pkg/memorystore/postgres.go
> Docker build fix

- pkg/memorystore/postgres.go
- pkg/memorystore/postgres_test.go
- Specify columns on insert/upsert.
- Add new test to ensure upsert after deletion does not overwrite deleted_at.
> Fix for #52

- pkg/memorystore/postgres.go
- pkg/memorystore/postgres_schema.go
- rearrange and split pg code to make it more maintainable
- add addition tests to ensure AppConfig is not a null pointer.
> rearrange and split pg code

- Dockerfile.postgres_flyio
pgvector build with no arch optimizations
> pgvector make OPTFLAGS="" in Dockerfile.postgres_flyio

- pkg/memorystore/postgres.go
- pkg/memorystore/postgres_search.go
- pkg/memorystore/postgres_search_test.go
- pkg/memorystore/postgres_test.go
- pkg/models/memorystore.go
- pkg/models/search.go
- pkg/server/handlers.go
- pkg/server/routes.go
- pkg/testutils/utils.go
Implement alongside vector search:
- hybrid search over metadata using jsonpath queries.
- hybrid search using message creation timestamps
> hybrid search

- config.yaml
- config/config.go
- config/models.go
- pkg/extractors/initialize.go
- pkg/extractors/intent_extractor.go
- pkg/extractors/intent_extractor_test.go
- pkg/extractors/prompts.go
- pkg/memorystore/postgres_metadata.go
- pkg/memorystore/postgres_metadata_test.go
- pkg/memorystore/postgres_test.go
- pkg/models/intent.go
PR for Intent Extractor implementation w/test
Intents run for every message (not a collection/memory)
> Intent extractor

- pkg/llms/llm_openai.go
- pkg/memorystore/postgres_metadata.go
- increase max openai api retries to 5
- increase openAIAPITimeout to 90 seconds
- improve put metadata error message
Ref #107
> bugfix 107

- config.yaml
- config/models.go
- http-client.private.env.json
- pkg/llms/llm_base.go
- pkg/llms/llm_openai.go
- pkg/llms/llm_openai_test.go
- feat: Use a custom URL for OpenAI API endpoints
- refactor OpenAI config
- minimal tests
Author: @drewbaumann . Thanks!
> feat: Alternative OpenAI Endpoint URL

- .github/workflows/swaggerui-deploy.yaml
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/server/routes.go
- disable gh action; update swagger file with version
> disable gh action; update swagger file with version

- README.md
- docker-compose.yaml
- readme update
- back out changes to dcoker compose
> readme update

- config.yaml
Intent extractor was erroneously disabled by default. Reverting.
> fix: default intent extractor to enabled

- pkg/store/postgres/schema.go
- pkg/store/postgres/schema_test.go
> fix: issue184 (updated_at not being updated)

- pkg/store/postgres/schema.go
- Increase ReadTimeout to 10 minutes as stop gap to deal with slow IVFFLAT index creation
- Create Schema indices only if they don't exist.
> fix: DB ReadTimeout; Index Creation

- Makefile
- pkg/web/static/js/dark-mode.js
- pkg/web/static/output.css
- pkg/web/tailwind.config.js
- pkg/web/templates/components/layout/dark_mode.html
- pkg/web/templates/components/layout/header.html
- pkg/web/templates/components/layout/layout.html
- pkg/web/templates/components/layout/scripts_top.html
- dark mode
- Makefile include js for gow
> feat: darkmode toggle

- pkg/extractors/summarizer.go
- pkg/llms/llm_base.go
- pkg/server/handlertools/tools.go
- pkg/store/postgres/documents.go
- pkg/store/postgres/session.go
- pkg/store/postgres/userstore.go
- pkg/store/postgres/userstore_test.go
- better error messages
- don't retry on 400 errors
> fix: Don't retry OpenAI calls on 400 errors; Better Error Messages

- pkg/store/postgres/schema.go
- Make MigrateEmbeddingDims more robust by using a TX to alter table. 
- Add debugging when getEmbeddingColumnWidth fails.
> fix: Make MigrateEmbeddingDims more robust

- pkg/tasks/router.go
- pkg/tasks/sql_queue.go
- Increase TaskRouter concurrency
- Reduce SQLSubscriber poll interval
> improv: Task Router Perf Improvements

- .github/workflows/docker-publish-cloud.yml
- .github/workflows/docker-publish.yml
> fix(CI): Add depot setup-action

- pkg/server/apihandlers/message_handlers.go
- pkg/server/routes.go
- pkg/store/postgres/message.go
GET /sessions/{sessionId}/message - Fetches all messages from a session
PATCH /sessions/{sessionId}/messages - Allows modification of the
metadata on a session
GET /sessions/{sessionId}/messages/{messageId} - Gets a specific message
from a session
> Added new API message endpoints
